spring.datasource.url: jdbc:h2:file:./camunda-h2-database
#spring.datasource.url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1

camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update


#logging.level.s7.Application=WARN
#logging.level.org.springframework.web=ERROR
#logging.level.com.javatechie.spring.logging.api=DEBUG

# Logging pattern for the console
#logging.pattern.console= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

#logging pattern for file
#logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#logging.file=C:/Users/bahota/Desktop/spring-boot-logging/api.log
#logging:
#  file:
#    path: F:\Logs
#  config: classpath:logback.xml

