spring.datasource.url: jdbc:h2:file:./camunda-h2-database
#spring.datasource.url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1

camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

#mail:
#  transport:
#    protocol: smtp
#  smtp:
#    host: smtp.gmail.com
#    port: 465
#    auth: true
#    ssl:
#      enable: true
#    socketFactory:
#      port: 465
#      class: javax.net.ssl.SSLSocketFactory
#  store:
#    protocol: imaps
#  imaps:
#    host: imap.gmail.com
#    port: 993
#    timeout: 10000
#  imap:
#      partialfetch: false
#  user: navishkatest@gmail.com
#  password: evjowagpbcgjikxy


#  mail.poll.folder=INBOX
#
#  mail.sender=USER@gmail.com
#  mail.sender.alias=SENDER_NAME

#  mail.attachment.download=true
#  mail.attachment.path=attachments


