spring.datasource.url: jdbc:h2:file:./camunda-h2-database
#spring.datasource.url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1

camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

